#!/bin/bash

#sudo umount /mnt/guest

qemu-system-x86_64 \
	-enable-kvm \
	-drive file=guest.raw,format=raw,cache=none \
	-m 8G \
	-kernel arch/x86_64/boot/bzImage \
	-append "root=/dev/sda2 rw console=ttyS0" \
	-net user,hostfwd=tcp::10022-:22 \
	-net nic \
	-device usb-ehci -device usb-host,vendorid=0x0582,productid=0x0160 \
	"$@"

	#-device VGA,vgamem_mb=64 \
#sudo mount -o loop,offset=2097152 guest.raw /mnt/guest
