name: libcapmix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install -y libasound2 libasound2-dev

    - name: Build libcapmix.so
      run: make -j4 lib/libcapmix.so

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libcapmix.so
        path: |
          obj/lib/libcapmix.so
