name: Release binaries

on:
  release:
    types: [created]

jobs:
  generate:
    name: Create release artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install -y libasound2 libasound2-dev

    - name: Build libcapmix.so
      run: make -j4 lib/libcapmix.so

    - name: Make tarball
      run: |
        mkdir -p dist/lib
        cp -P obj/lib/libcapmix.so* dist/lib
        tar zcf capmix.tar.gz -C dist lib

    - name: github-action-publish-binaries
      uses: skx/github-action-publish-binaries@release-2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'capmix.tar.gz'
