name: Release binaries

on:
  release:
    types: [created]

jobs:
  generate:
    name: Create release artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install -y libasound2 libasound2-dev

    - name: Build libcapmix and binaries
      run: |
        make -j4 lib/libcapmix.so
        make bin/list-memory
        make bin/main-dynamic
        make bin/capmixer-dynamic

    - name: Make tarball
      run: |
        make tarball

    - name: github-action-publish-binaries
      uses: skx/github-action-publish-binaries@release-2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'capmix.tar.gz'
